### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Freddrickk** [savoirfairelinux/PiKake#1]
- [x] Background preload
- [x] Tab management via web interface
  - Add/Remove/Edit tabs
  - Configure tabs (display time, refresh, vertical scroll delay)
- [x] Automatic vertical scroll
- [ ] Admin page
- [ ] Information page on web interface (ip, ssh credentials)
- [x] Pikake args to set config file path
- [x] HTTP authentication
